# Generated by Django 4.2 on 2023-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(max_length=10000, null=True, upload_to='measurement/static/images', verbose_name='Изображение'),
        ),
    ]
